"""Adding area id to assistance table

Revision ID: 2bd7eec4f51c
Revises: bfa7cdbb29cf
Create Date: 2021-08-19 15:48:11.900223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd7eec4f51c'
down_revision = 'bfa7cdbb29cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'assistance', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistance', type_='unique')
    op.drop_column('assistance', 'area_id')
    # ### end Alembic commands ###
