"""making social case id not required

Revision ID: 37b22d1bd5e4
Revises: a92cf8ff0e7b
Create Date: 2021-12-09 14:48:44.296626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b22d1bd5e4'
down_revision = 'a92cf8ff0e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistance', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assistance', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'report_item', ['id'])
    op.create_unique_constraint(None, 'visit_report', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_report', type_='unique')
    op.drop_constraint(None, 'report_item', type_='unique')
    op.alter_column('assistance', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assistance', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
