"""removing is active status from visit table

Revision ID: 3e16a96e65a8
Revises: 8ffe87c069fb
Create Date: 2021-11-15 16:42:00.203343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e16a96e65a8'
down_revision = '8ffe87c069fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'is_active')
    op.create_unique_constraint(None, 'visit_revision', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_revision', type_='unique')
    op.add_column('visit', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
