"""Adding title to assistance table

Revision ID: 4314313fb4a5
Revises: 6bb5cc0605bc
Create Date: 2021-08-09 20:24:23.246446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4314313fb4a5'
down_revision = '6bb5cc0605bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance', sa.Column('title', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'assistance', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistance', type_='unique')
    op.drop_column('assistance', 'title')
    # ### end Alembic commands ###
