"""Adding date to construction assistance table

Revision ID: 560dc734c5fe
Revises: 8e088653de8f
Create Date: 2021-08-24 17:01:08.900928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560dc734c5fe'
down_revision = '8e088653de8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance_construction', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistance_construction', 'date')
    # ### end Alembic commands ###
