"""attachement file key edit

Revision ID: 68030bce8db3
Revises: 37b22d1bd5e4
Create Date: 2021-12-15 20:09:29.404828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68030bce8db3'
down_revision = '37b22d1bd5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'file_key',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'file_key',
                    existing_type=sa.VARCHAR(length=40),
                    nullable=False)
    # ### end Alembic commands ###
