"""creating assistance table

Revision ID: 6bb5cc0605bc
Revises: 
Create Date: 2021-08-06 16:54:19.676590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb5cc0605bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('type_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('start_date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('shift_id', sa.Integer(), nullable=False),
                    sa.Column('shift_name', sa.String(
                        length=120), nullable=True),
                    sa.Column('status', sa.String(length=15), nullable=False),
                    sa.Column('assigned_id', sa.Integer(), nullable=False),
                    sa.Column('business_id', sa.Integer(), nullable=False),
                    sa.Column('construction_id', sa.Integer(), nullable=False),
                    sa.Column('business_name', sa.String(
                        length=150), nullable=True),
                    sa.Column('construction_name', sa.String(
                        length=150), nullable=True),
                    sa.Column('observation', sa.String(
                        length=500), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistance')
    # ### end Alembic commands ###
