"""adding is active to visit table

Revision ID: 724938ea445d
Revises: c6b177fdbb9d
Create Date: 2021-10-29 14:41:13.975057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724938ea445d'
down_revision = 'c6b177fdbb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'is_active')
    # ### end Alembic commands ###
