"""adding attached key to assistance table

Revision ID: 7380f50335e5
Revises: 560dc734c5fe
Create Date: 2021-08-24 21:47:07.980759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7380f50335e5'
down_revision = '560dc734c5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance', sa.Column('attached_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistance', 'attached_key')
    # ### end Alembic commands ###
