"""adding attachment list

Revision ID: 741f6337b5f9
Revises: 8d53e25b6c69
Create Date: 2021-11-11 15:49:02.436407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741f6337b5f9'
down_revision = '8d53e25b6c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assistance_attachment_id_fkey', 'assistance', type_='foreignkey')
    op.drop_column('assistance', 'attachment_id')
    op.add_column('attachment', sa.Column('assistance_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'attachment', ['id'])
    op.create_foreign_key(None, 'attachment', 'assistance', ['assistance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_constraint(None, 'attachment', type_='unique')
    op.drop_column('attachment', 'assistance_id')
    op.add_column('assistance', sa.Column('attachment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('assistance_attachment_id_fkey', 'assistance', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###
