"""adding attachment table

Revision ID: 8d53e25b6c69
Revises: e3f06c17d268
Create Date: 2021-11-10 14:31:22.247790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d53e25b6c69'
down_revision = 'e3f06c17d268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('file_key', sa.String(length=40), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.String(length=20), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('assistance', sa.Column('attachment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assistance', 'attachment', ['attachment_id'], ['id'])
    op.drop_column('assistance', 'attached_key')
    op.drop_column('assistance', 'attached_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance', sa.Column('attached_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('assistance', sa.Column('attached_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assistance', type_='foreignkey')
    op.drop_column('assistance', 'attachment_id')
    op.drop_table('attachment')
    # ### end Alembic commands ###
