"""Adding area_name, employee_lastname to assistance table

Revision ID: 8e088653de8f
Revises: ca10d52dcccc
Create Date: 2021-08-20 07:12:35.137934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e088653de8f'
down_revision = 'ca10d52dcccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance', sa.Column('employee_lastname', sa.String(length=100), nullable=False))
    op.add_column('assistance', sa.Column('area_name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'assistance', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistance', type_='unique')
    op.drop_column('assistance', 'area_name')
    op.drop_column('assistance', 'employee_lastname')
    # ### end Alembic commands ###
