"""Adding employee_id to assistance table

Revision ID: 8f416a6a7403
Revises: ac535a1f19fc
Create Date: 2021-08-19 19:04:19.122478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f416a6a7403'
down_revision = 'ac535a1f19fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance', sa.Column('employee_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistance', 'employee_id')
    # ### end Alembic commands ###
