"""adding close status to visit table

Revision ID: 8ffe87c069fb
Revises: 741f6337b5f9
Create Date: 2021-11-12 16:31:03.088127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffe87c069fb'
down_revision = '741f6337b5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_revision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comments', sa.String(length=800), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('visit', sa.Column('is_close', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('visit', sa.Column('is_close_pending', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('visit', sa.Column('close_revision_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visit', 'visit_revision', ['close_revision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_column('visit', 'close_revision_id')
    op.drop_column('visit', 'is_close_pending')
    op.drop_column('visit', 'is_close')
    op.drop_table('visit_revision')
    # ### end Alembic commands ###
