"""Adding report atrr to visit table

Revision ID: 91229af60c0d
Revises: 7380f50335e5
Create Date: 2021-08-25 17:01:16.699849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91229af60c0d'
down_revision = '7380f50335e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('report_url', sa.String(length=255), nullable=True))
    op.add_column('visit', sa.Column('report_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'report_key')
    op.drop_column('visit', 'report_url')
    # ### end Alembic commands ###
