"""change source systema and source business

Revision ID: ac535a1f19fc
Revises: 2bd7eec4f51c
Create Date: 2021-08-19 17:59:15.015504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac535a1f19fc'
down_revision = '2bd7eec4f51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
