"""adding worker quantity to visit table

Revision ID: b6fd90ff92d8
Revises: 5e7f88e93104
Create Date: 2021-11-15 22:36:17.692632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fd90ff92d8'
down_revision = '5e7f88e93104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('company_workers', sa.Integer(), nullable=True))
    op.add_column('visit', sa.Column('outsourced_workers', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'visit_report_item', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_report_item', type_='unique')
    op.drop_column('visit', 'outsourced_workers')
    op.drop_column('visit', 'company_workers')
    # ### end Alembic commands ###
