"""Adding assistance table

Revision ID: bfa7cdbb29cf
Revises: 063493de7e8c
Create Date: 2021-08-19 15:38:25.057458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa7cdbb29cf'
down_revision = '063493de7e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source_system', sa.Integer(), nullable=False),
    sa.Column('source_business', sa.Integer(), nullable=False),
    sa.Column('attention_place', sa.String(length=255), nullable=False),
    sa.Column('contact_method', sa.String(length=255), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('construction_name', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('management_id', sa.Integer(), nullable=False),
    sa.Column('is_social_case', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('company_report', sa.String(length=2), nullable=False),
    sa.Column('observation', sa.String(length=255), nullable=False),
    sa.Column('assigned_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('attached_url', sa.String(length=1024), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistance')
    # ### end Alembic commands ###
