"""business id and construction id non required at visit table

Revision ID: dea9f6438a24
Revises: 91229af60c0d
Create Date: 2021-09-13 16:30:34.289011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea9f6438a24'
down_revision = '91229af60c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visit', 'construction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'construction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
