"""making business and construction no required at assistance table

Revision ID: e3f06c17d268
Revises: 3747450267f3
Create Date: 2021-11-08 17:18:34.929747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f06c17d268'
down_revision = '3747450267f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistance', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assistance', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('assistance', 'construction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assistance', 'construction_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistance', 'construction_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('assistance', 'construction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assistance', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('assistance', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
